# -*- mode: conf; -*-

# for sample configuration, cf. https://github.com/toml-lang/toml/tree/master/examples
[chain]
contract_src_dir = "cpchain/assets/chain/contracts/Trading.sol"
contract_json = "cpchain/assets/chain/build/Trading.json"
registrar_json = "cpchain/assets/chain/registrar.json"
core_contract = "Trading"
is_test = true
rpc_provider_addr = ""

[storage.s3]
bucket = "cpchain-bucket"
secret_access_key = "TlLYyyb6avQvdf8BU0UzEj7P83tbVjSLyv9kTppd"
access_key_id = "AKIAI34GNTRZVNJ5ZMZA"

[storage.ipfs]
addr = '192.168.0.132'
port = 5001

[wallet]
dbpath = "cpchain/assets/wallet/wallet.db"

[proxy]
server_port = 8000
server_key = 'cpchain/assets/proxy/key/server.key'
server_crt = 'cpchain/assets/proxy/key/server.crt'
dbpath = "cpchain/assets/proxy/proxy.db"

[market]
server_addr = "192.168.0.132"
server_port = 8083
