# -*- mode: conf; -*-

# for sample configuration, cf. https://github.com/toml-lang/toml/tree/master/examples
[chain]
contract_src_dir = ""
contract_build_dir = ""
core_contract = "Trade"


[storage.s3]
bucket = "cpchain-bucket"
secret_access_key = "TlLYyyb6avQvdf8BU0UzEj7P83tbVjSLyv9kTppd"
access_key_id = "AKIAI34GNTRZVNJ5ZMZA"